# Generated by Django 6.0.5 on 2026-06-17 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('pergunta', models.TextField()),
                ('numero_maximo_selecao', models.IntegerField(default=1)),
                ('contem_dado_sensivel', models.BooleanField(default=False,
                 help_text='Sinaliza se a pergunta exige governanca estrita (ex: alergias)')),
            ],
            options={
                'verbose_name': 'Caracteristica de Atendimento',
                'verbose_name_plural': 'Caracteristicas de Atendimento',
                'db_table': 'caracteristica_atendimento',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apelido', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('consentimento_dados_sensiveis', models.BooleanField(default=False)),
                ('anonimizado', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'db_table': 'estabelecimento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[
                 ('admin', 'Admin'), ('profissional', 'Profissional'), ('gerente', 'Gerente')], max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('termos_aceitos', models.BooleanField(default=False)),
                ('data_consentimento', models.DateTimeField(blank=True, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaAtendimentoOpcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ilustracao', models.CharField(blank=True, max_length=500)),
                ('caracteristica_atendimento', models.ForeignKey(db_column='id_caracteristica_atendimento',
                 on_delete=django.db.models.deletion.CASCADE,
                 related_name='opcoes', to='core.caracteristicaatendimento')),
                ('nivel_superior', models.ForeignKey(blank=True, db_column='id_nivel_superior', null=True,
                 on_delete=django.db.models.deletion.SET_NULL,
                 related_name='subdivisoes', to='core.caracteristicaatendimentoopcao')),
            ],
            options={
                'verbose_name': 'Opcao de Caracteristica de Atendimento',
                'verbose_name_plural': 'Opcoes de Caracteristica de Atendimento',
                'db_table': 'caracteristica_atendimento_opcao',
            },
        ),
        migrations.CreateModel(
            name='CategoriaCusto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ilustracao', models.CharField(blank=True, max_length=500)),
                ('nivel_superior', models.ForeignKey(blank=True, db_column='id_nivel_superior', null=True,
                 on_delete=django.db.models.deletion.SET_NULL,
                 related_name='subcategorias', to='core.categoriacusto')),
            ],
            options={
                'verbose_name': 'Categoria de Custo',
                'verbose_name_plural': 'Categorias de Custo',
                'db_table': 'categoria_custo',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('duracao', models.IntegerField(help_text='Duracao em minutos')),
                ('cliente', models.ForeignKey(db_column='id_cliente',
                 on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.cliente')),
                ('estabelecimento', models.ForeignKey(db_column='id_estabelecimento',
                 on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.estabelecimento')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'db_table': 'atendimento',
            },
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atendimento', models.ForeignKey(blank=True, db_column='id_atendimento', null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='core.atendimento')),
                ('categoria_custo', models.ForeignKey(db_column='id_categoria_custo',
                 on_delete=django.db.models.deletion.PROTECT, related_name='custos', to='core.categoriacusto')),
                ('estabelecimento', models.ForeignKey(db_column='id_estabelecimento',
                 on_delete=django.db.models.deletion.PROTECT, related_name='custos', to='core.estabelecimento')),
            ],
            options={
                'verbose_name': 'Custo',
                'verbose_name_plural': 'Custos',
                'db_table': 'custo',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='estabelecimento',
            field=models.ForeignKey(db_column='id_estabelecimento', on_delete=django.db.models.deletion.PROTECT,
                                    related_name='clientes', to='core.estabelecimento'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atendimento', models.ForeignKey(db_column='id_atendimento',
                 on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.atendimento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoCaracteristica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atendimento', models.ForeignKey(db_column='id_atendimento',
                 on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='core.atendimento')),
                ('opcao', models.ForeignKey(
                 db_column='id_caracteristica_atendimento_opcao',
                 on_delete=django.db.models.deletion.PROTECT,
                 related_name='atendimento_caracteristicas', to='core.caracteristicaatendimentoopcao')),
            ],
            options={
                'verbose_name': 'Caracteristica do Atendimento',
                'verbose_name_plural': 'Caracteristicas do Atendimento',
                'db_table': 'atendimento_caracteristica',
                'unique_together': {('atendimento', 'opcao')},
            },
        ),
        migrations.CreateModel(
            name='EstabelecimentoUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estabelecimento', models.ForeignKey(
                 db_column='id_estabelecimento',
                 on_delete=django.db.models.deletion.CASCADE,
                 related_name='estabelecimento_usuarios', to='core.estabelecimento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE,
                 related_name='estabelecimento_usuarios', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Estabelecimento Usuario',
                'verbose_name_plural': 'Estabelecimentos Usuarios',
                'db_table': 'estabelecimento_usuario',
                'unique_together': {('estabelecimento', 'usuario')},
            },
        ),
    ]
