# Generated by Django 5.2.15 on 2026-06-18 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estabelecimentousuario_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimentousuario',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='consentimento_dados_sensiveis',
        ),
    ]
