# Generated by Django 6.0.5 on 2026-06-17 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                 help_text=(
                  'Designates that this user has all permissions without explicitly assigning them.'
                 ),
                 verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[
                 ('admin', 'Admin'), ('profissional', 'Profissional'), ('gerente', 'Gerente')], max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('termos_aceitos', models.BooleanField(default=False)),
                ('data_consentimento', models.DateTimeField(blank=True, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='security_usuario_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True,
                 related_name='security_usuario_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'security_usuario',
            },
        ),
    ]
