name: Docs

on:
  push:
    branches: ["main", "developer"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
  pull_request: # <- Adicionado: Testa as alterações antes de aceitar o Merge na main
    branches: ["main"]
    paths:
      - "docs/**"
      - "mkdocs.yml"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Publicar no GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar MkDocs e plugins
        run: |
          pip install \
            mkdocs-material \
            mkdocs-minify-plugin

      # PASSO 1: Roda sempre (na developer, na main e em PRs). 
      # Se houver link quebrado ou erro, o workflow para aqui.
      - name: Validar Documentação (Modo Estrito)
        run: mkdocs build --strict

      # PASSO 2: O deploy real SÓ acontece se o commit for na branch main
      - name: Publicar no GitHub Pages
        if: github.ref == 'refs/heads/main' # <- Filtro de segurança
        run: mkdocs gh-deploy --force